apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 1
  template:
  metadata:
    labels:
     app: flask-app
  spec:
    containers:
    - name: flask-app
      image: flaskapp:latest
      imagePullPolicy: "IfNotPresent"
      ports:
      - containerPort: 5000
    volumes:
      - name: flask-app
        persistentVolumeClaim:
          claimName: appclaim1